Drag and drop
typefaceoff/typefaceoff pull request #22
Opened 2023-08-19 02:31 UTC by JC4github

### Changes

Describe the Pull Request here. Add any references and info to help reviewers understand your changes.

- Add the component to handle drag and drop of .otf files 
- Add the text preview component to render the uploaded font

### Issue ticket number(s)

Enter the issue numbers resolved by this pull request

- 17

### Checklist

- [ ] Documented
- [ ] Linting tests successful
- [ ] merge updated prod branch into development branch

2023-08-19 03:13 UTC, jaskfla requested changes
I’m not qualified to review the `.tsx` files, so will refrain from commenting on those.

The key suggestion I’ve got is to make margins and padding agnostic to whether the language is LTR or RTL. I’ve made suggestions for these.

Based on the screenshot you’ve shared in Discord, though, looks pretty solid!

2023-08-19 03:13 UTC, jaskfla commented on src/App.css
>  .logo {
The the `logo` class not get removed in the recent template? We might be able to clean some of these away.

We should at least should be avoiding `will-change` except as a last resort.

2023-08-19 03:13 UTC, jaskfla commented on src/App.css
> +    font-family: "Your-Selected-Font", sans-serif;
Does the replacement get done dynamically? Perhaps we can get away with even simpler here. 🤔 

```suggestion
    font-family: system-ui, 'Segoe UI', sans-serif;
```

2023-08-19 03:13 UTC, jaskfla commented on src/App.css
> +    display: flex;
This comment isn’t specific to this line, but do we want to impose some sort of total ordering of CSS properties?

Would make changes over time wider, but I have to admit I’m not sure how to do this.

2023-08-19 03:13 UTC, jaskfla commented on src/App.css
> +    margin-top: 20px;
```suggestion
    margin-block-start: 20px;
```

2023-08-19 03:13 UTC, jaskfla commented on src/App.css
> +    margin-bottom: 60px;
```suggestion
    margin-block-end: 60px;
```

2023-08-19 03:13 UTC, jaskfla commented on src/App.css
> +    margin-left: 20px;
```suggestion
    margin-inline: 20px;
```

2023-08-19 03:13 UTC, jaskfla commented on src/App.css
> +    margin-right: 20px;
```suggestion
```

2023-08-19 03:13 UTC, jaskfla commented on src/components/FontPreviewLeft.tsx
> +      src: url(${fontUrl}) format('opentype');
```suggestion
      src: url(${fontUrl}) format('opentype');
      font-display: swap;
```

2023-08-19 03:13 UTC, jaskfla commented on src/components/FontPreviewRight.tsx
> +      src: url(${fontUrl}) format('opentype');
```suggestion
      src: url(${fontUrl}) format('opentype');
      font-display: swap;
```

2023-08-19 03:13 UTC, jaskfla commented on src/index.css
> +    font-weight: 500;
Not much reason for links to be slightly heavier in weight. A little baffled the template does this 🤨 

```suggestion
```

2023-08-19 03:13 UTC, jaskfla commented on src/styles/FontUploader.css
> +    margin-top: 10px;
```suggestion
    margin-block-start: 10px;
```

2023-08-19 03:13 UTC, jaskfla commented on src/styles/FontUploader.css
> +    padding-left: 40px;
```suggestion
    padding-inline-start: 40px;
```

2023-08-20 07:42 UTC, joaomad247 approved these changes
LGTM 👍

2023-08-20 07:42 UTC, joaomad247 commented on src/components/FontUploader.tsx
> +    const otfFiles = files.filter((file) => file.name.endsWith('.otf'));
Are all font files .otf? Can't some of them also be .ttf like the ones you download from https://fonts.google.com/ ?

2023-08-20 08:21 UTC, merged