Page title
typefaceoff/typefaceoff pull request #40
Opened 2023-08-24 22:56 UTC by JC4github

### Changes

Describe the Pull Request here. Add any references and info to help reviewers understand your changes.

- Changed page title and logo

### Tests applied

What testing has been applied to validate changes are accurate and correct

- visual inspection 

### Issue ticket number(s)

Enter the issue numbers resolved by this pull request

- 37

### Checklist

- [ ] Documented
- [ ] Linting tests successful
- [ ] merge updated prod branch into development branch

2023-08-24 23:29 UTC, jaskfla requested changes
Just the capitalisation of the title, and perhaps reinstating Husky files.

Otherwise looks good!

2023-08-24 23:29 UTC, jaskfla commented on .husky/.gitignore
Any chance you could put the `.husky/` file back?

We can reconfigure the pre-commit hooks later, as it seems we have at least two people having trouble. But at least for now it remains part of the recommended project setup.

2023-08-24 23:29 UTC, jaskfla commented on index.html
> +    <title>TypeFaceOff</title>
Seeing as we’ve now decided on an “official” capitalisation, might get you to update this.

Sorry about the busywork 😅

2023-08-24 23:29 UTC, jaskfla commented on typefaceoff_logo.svg
Nice!

2023-08-24 23:51 UTC, JC4github commented on .husky/.gitignore
the .husky/ files are in my project on VScode, I'm not sure why they are not added to the commit.

2023-08-24 23:59 UTC, jaskfla reviewed
~~Looks like the `pre-commit` file you put back was empty.~~

~~Otherwise~~ looks good to merge 🥳

2023-08-24 23:59 UTC, jaskfla commented on .husky/pre-commit
```suggestion
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
```

2023-08-25 00:04 UTC, jaskfla approved these changes

2023-08-25 00:04 UTC, merged